### DISCUSSION TITLE
K3S doesn’t wanna connect

### DISCUSSION THREAD

**Discussion by luna-dj** [wiredoor/wiredoor#40] [Q&A] [answered]
I have a problem with wire door not being able to reach the port in nginx.default.svc.cluster.local at port 80
Is there some documentation on how to do this

**Comment by dmesad** [comment]
Hi @luna-dj! Thanks for reaching out. 

To better assist you, could you please provide a bit more context about your setup and what you're trying to achieve?

1. Have you created a gateway node for your cluster with the correct subnet, as shown [here](https://www.wiredoor.net/docs/kubernetes-gateway#1-identify-your-clusters-service-subnet)?
2. Have you installed the Kubernetes gateway in your K3s cluster using the Helm chart, and provided the correct `wiredoor.server` and `wiredoor.token` values?
3. You are trying to expose `nginx.default.svc.cluster.local:80`, Have you configured a service for your nginx pod in the `default` namespace?

Any additional details about your deployment or the error you're encountering would be really helpful!

**Reply by luna-dj** [reply]
1. yes it's 10.43.0.0/12 
2. it's connected
3. i tried nginx-service.default.svc.cluster.local and port 80


i have this kube manifest file.

deployment.yaml 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
```
service.yaml 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
```

it's running in k3s on 3 master nodes and 2 worker nodes
