### DISCUSSION TITLE
Crowdsec

### DISCUSSION THREAD

**Discussion by zerodarkzone** [wiredoor/wiredoor#48] [Ideas]
Hi,

It would be nice to include crowdsec in the docker compose example. This would make wiredoor a litle more secure for exposing services.

**Comment by dmesad** [comment]
Great suggestion!

Are you familiar with how to integrate it properly in a Docker Compose setup? If you have any recommendations or would like to contribute a working example, feel free to share it. Even better if you’re up for submitting a PR! We’d be happy to review it.

**Reply by zerodarkzone** [reply]
Hi,
I'm not an expert but I'll try to configure a working example. I think it is better to modify the wiredoor docker image to install the crowdsec bouncer and modify the nginx config file to use it (This should be configurable in case someone does not want to use it).
It is possible to install and configure crowdsec using the compose file only, but without the bouncer you would only be able to detect attacks without being able to do anythong about them.

**Reply by buildplan** [reply]
> Great suggestion!
> 
> Are you familiar with how to integrate it properly in a Docker Compose setup? If you have any recommendations or would like to contribute a working example, feel free to share it. Even better if you’re up for submitting a PR! We’d be happy to review it.

I integrated crowdsec and it's working really well. We already have logs for nginx which I am targeting here is my docker compose - thought I share it might help 

```
networks:
  default:
    driver: bridge
    name: wiredoor

services:
  # --- wiredoor ---
  wiredoor:
    image: ghcr.io/wiredoor/wiredoor:latest
    container_name: wiredoor
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./certbot:/etc/letsencrypt
      - ./logs:/var/log/nginx
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 51820:51820/udp
      # - 32760-32767:32760-32767 #ports for tcp/udp resources
    sysctls:
      - net.ipv4.ip_forward=1
    logging:
      driver: "json-file"
      options: { max-size: "10m", max-file: "3" }
    deploy:
      resources:
        limits: { cpus: '0.50', memory: 512M }
        reservations: { cpus: '0.25', memory: 256M }
    healthcheck:
      test: ["CMD-SHELL", "ss -uln | grep -q ':51820' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

  # --- crowdsec ---
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./logs:/var/log/nginx_logs:ro
      - ./crowdsec/config:/etc/crowdsec/
      - ./crowdsec/data:/var/lib/crowdsec/data/
    environment:
      - COLLECTIONS=crowdsecurity/nginx crowdsecurity/nginx-proxy-manager
      - TZ=Europe/London
      - GID=$(id -g)
    ports:
      - "127.0.0.1:8080:8080"
    logging:
      driver: "json-file"
      options: { max-size: "10m", max-file: "3" }
    deploy:
      resources:
        limits: { cpus: '0.50', memory: 512M }
    healthcheck:
      test: ["CMD", "cscli", "lapi", "status"]
      interval: 15s
      timeout: 10s
      retries: 4
      start_period: 30s

```
