### ISSUE TITLE
Nginx host not found in upstream

### ISSUE THREAD

**Issue by ginjiruu** [wiredoor/wiredoor#45]
### Environment

VM/K8S

### Describe the bug

When trying to expose a plain tcp service the webui reports back a success, however the backend reports an error in the nginx config

### Steps to reproduce

1. Create new tcp route
2. Save it
3. Error

### Logs or error output

```shell
nginx:
File /etc/nginx/stream.d/n2s1_stream.conf does not exists
Error: Command failed: nginx -t
nginx: [emerg] host not found in upstream "haproxy-service.haproxy.svc.cluster.local:25" in /etc/nginx/stream.d/n2s1_stream.conf:4
nginx: configuration file /etc/nginx/nginx.conf test failed

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1104:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:524:28)
    at Pipe.<anonymous> (node:net:343:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'nginx -t'
}
Nginx failed testing file /etc/nginx/stream.d/n2s1_stream.conf

nslookup from inside container
2ebfefc117e8:/etc/nginx# nslookup haproxy-service.haproxy.svc.cluster.local 10.30.0.2
Server:		10.30.0.2
Address:	10.30.0.2:53


Name:	haproxy-service.haproxy.svc.cluster.local
Address: 10.43.88.193

2ebfefc117e8:/etc/nginx#
```

### Wiredoor version

1.1.0

**Comment by dmesad** [comment]
Can you share the file contents of `/etc/nginx/stream.d/n2s1_stream.conf`?

**Comment by dmesad** [comment]
Please double-check the following:

1. Ensure the TCP_SERVICES_PORT_RANGE variable is set in your environment. For example:

```bash
TCP_SERVICES_PORT_RANGE=32760-32767
```

2. Make sure you're exposing that entire port range in your `docker-compose.yml` file:

```yaml
ports:
  - "32760-32767:32760-32767"
```

3. Delete any previously created TCP services.

4. After updating the config, restart the container to apply the changes. And recreate your TCP services.

Let me know if the issue persists after verifying those settings.

**Comment by ginjiruu** [comment]
docker-compose.yml
```
services:
  wiredoor:
    image: ghcr.io/wiredoor/wiredoor:latest
    container_name: wiredoor
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - wiredoor-data:/data
      - wiredoor-certbot:/etc/letsencrypt
      # - ./wiredoor-logs:/var/log/nginx        # <--- Optional: Mount for collecting NGINX logs
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 51820:51820/udp                        # Must match with VPN_PORT in .env
      - 23-52:23-52
      - 54-150:54-150                # Must match with TCP_SERVICES_PORT_RANGE in .env
    sysctls:
      - net.ipv4.ip_forward=1

volumes:
  wiredoor-data:
  wiredoor-certbot:
```
.env
```
# Wiredoor admin credentials
ADMIN_EMAIL=REDACTED
ADMIN_PASSWORD=REDACTED

# VPN Information
VPN_HOST=REDACTED        # Required. Public address that clients will connect to
VPN_PORT=51820                          # Default WireGuard UDP port
VPN_SUBNET=10.30.0.0/24                 # Subnet for clients (in CIDR format)

# TCP Port range
TCP_SERVICES_PORT_RANGE=23-32767     # Optional. Port range to expose TCP/UDP services

# TCP/UDP Exposure (Public Port Range)
TZ=America/New_York                     # Time zone (recommended for logging)
```
